{{/* Create a configmap with all the insensitive environment variable data if not exist */}}
{{- $config := (lookup "v1" "ConfigMap" (include "appwrite.namespace" .) (printf "%s-env" (include "appwrite.fullname" .))) }}
{{- if not $config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "appwrite.fullname" . }}-env"
  namespace: "{{ include "appwrite.namespace" . }}"
  labels:
    app.kubernetes.io/name: "{{ include "appwrite.fullname" . }}-env"
    {{- include "appwrite.labels" . | nindent 4 }}
data:
  _APP_ENV: {{ .Values.environments.env | quote }}
  _APP_LOCALE: {{ .Values.environments.locale | quote }}
  _APP_WORKER_PER_CORE: {{ .Values.environments.worker.perCore | quote }}
  _APP_CONSOLE_WHITELIST_ROOT: {{ .Values.environments.console.whitelist.root | quote }}
  _APP_CONSOLE_WHITELIST_EMAILS: {{ .Values.environments.console.whitelist.emails | quote }}
  _APP_CONSOLE_WHITELIST_IPS: {{ .Values.environments.console.whitelist.ips | quote }}
  _APP_SYSTEM_EMAIL_NAME: {{ .Values.environments.system.email.name | quote }}
  _APP_SYSTEM_EMAIL_ADDRESS: {{ .Values.environments.system.email.address | quote }}
  _APP_SYSTEM_SECURITY_EMAIL_ADDRESS: {{ .Values.environments.system.security.emailAddress | quote }}
  _APP_SYSTEM_RESPONSE_FORMAT: {{ .Values.environments.system.response.format | quote }}
  _APP_OPTIONS_ABUSE: {{ .Values.environments.options.abuse | quote }}
  _APP_OPTIONS_ROUTER_PROTECTION: {{ .Values.environments.options.routerProtection | quote }}
  _APP_OPTIONS_FORCE_HTTPS: {{ .Values.environments.options.forceHttps | quote }}
  _APP_OPTIONS_FUNCTIONS_FORCE_HTTPS: {{ .Values.environments.options.functions.forceHttps | quote }}
  _APP_DOMAIN: {{ .Values.environments.domain.app | quote }}
  _APP_DOMAIN_FUNCTIONS: {{ .Values.environments.domain.functions | quote }}
  _APP_DOMAIN_TARGET: {{ .Values.environments.domain.target | quote }}
  _APP_REDIS_HOST: {{ .Values.environments.redis.host | default (printf "%s-redis-master.%s.svc.%s" .Release.Name (include "appwrite.namespace" .) .Values.clusterDomain) | quote }}
  _APP_REDIS_PORT: {{ .Values.environments.redis.port | default 6379 | quote }}
  _APP_DB_HOST: {{ .Values.environments.database.host | default (printf "%s-mariadb.%s.svc.%s" .Release.Name (include "appwrite.namespace" .) .Values.clusterDomain) | quote }}
  _APP_DB_PORT: {{ .Values.environments.database.port | default 3306 | quote }}
  _APP_DB_SCHEMA: {{ .Values.environments.database.schema | quote }}
  _APP_STORAGE_DEVICE: {{ .Values.environments.storage.device | quote }}
  _APP_STORAGE_S3_ENDPOINT_URL: {{ .Values.environments.storage.s3.endpointUrl | quote }}
  _APP_STORAGE_S3_REGION: {{ .Values.environments.storage.s3.region | quote }}
  _APP_STORAGE_S3_BUCKET: {{ .Values.environments.storage.s3.bucket | quote }}
  _APP_STORAGE_DO_SPACES_REGION: {{ .Values.environments.storage.doSpaces.region | quote }}
  _APP_STORAGE_DO_SPACES_BUCKET: {{ .Values.environments.storage.doSpaces.bucket | quote }}
  _APP_STORAGE_BACKBLAZE_REGION: {{ .Values.environments.storage.backblaze.region | quote }}
  _APP_STORAGE_BACKBLAZE_BUCKET: {{ .Values.environments.storage.backblaze.bucket | quote }}
  _APP_STORAGE_LINODE_REGION: {{ .Values.environments.storage.linode.region | quote }}
  _APP_STORAGE_LINODE_BUCKET: {{ .Values.environments.storage.linode.bucket | quote }}
  _APP_STORAGE_WASABI_REGION: {{ .Values.environments.storage.wasabi.region | quote }}
  _APP_STORAGE_WASABI_BUCKET: {{ .Values.environments.storage.wasabi.bucket | quote }}
  _APP_STORAGE_ANTIVIRUS: {{ .Values.environments.storage.antivirus.enabled | quote }}
  _APP_STORAGE_ANTIVIRUS_HOST: {{ .Values.environments.storage.antivirus.host | default (printf "clamav.%s.svc.%s" (include "appwrite.namespace" .) .Values.clusterDomain) | quote }}
  _APP_STORAGE_ANTIVIRUS_PORT: {{ .Values.environments.storage.antivirus.port | default 3310 | quote }}
  _APP_INFLUXDB_HOST: {{ .Values.environments.influxdb.host | default (printf "%s-influxdb.%s.svc.%s" .Release.Name (include "appwrite.namespace" .) .Values.clusterDomain) | quote }}
  _APP_INFLUXDB_PORT: {{ .Values.environments.influxdb.port | default 8086 | quote }}
  _APP_STATSD_HOST: {{ .Values.environments.statsd.host | default (printf "telegraf.%s.svc.%s" (include "appwrite.namespace" .) .Values.clusterDomain) | quote }}
  _APP_STATSD_PORT: {{ .Values.environments.statsd.port | default 8125 | quote }}
  _APP_SMTP_HOST: {{ .Values.environments.smtp.host | quote }}
  _APP_SMTP_PORT: {{ .Values.environments.smtp.port | default 25 | quote }}
  _APP_SMTP_SECURE: {{ .Values.environments.smtp.secure | quote }}
  _APP_SMS_PROVIDER: {{ .Values.environments.sms.provider | default "sms://username:password@mock" | quote }}
  _APP_SMS_FROM: {{ .Values.environments.sms.from | default "+123456789" | quote }}
  _APP_STORAGE_LIMIT: {{ required "A valid storage limit is required!" .Values.environments.storage.limit | quote }}
  _APP_STORAGE_PREVIEW_LIMIT: {{ required "A valid preview storage limit is required!" .Values.environments.storage.previewLimit | quote }}
  _APP_FUNCTIONS_SIZE_LIMIT: {{ required "A valid size limit for functions is required!" .Values.environments.functions.sizeLimit | quote }}
  _APP_FUNCTIONS_TIMEOUT: {{ .Values.environments.functions.timeout | quote }}
  _APP_FUNCTIONS_BUILD_TIMEOUT: {{ .Values.environments.functions.buildTimeout | quote }}
  _APP_FUNCTIONS_CPUS: {{ .Values.environments.functions.cpus | quote }}
  _APP_FUNCTIONS_MEMORY: {{ .Values.environments.functions.memory | quote }}
  _APP_FUNCTIONS_INACTIVE_THRESHOLD: {{ .Values.environments.functions.inactiveThreshold | quote }}
  _APP_FUNCTIONS_MAINTENANCE_INTERVAL: {{ .Values.environments.functions.maintenanceInterval | quote }}
  _APP_EXECUTOR_HOST: {{ .Values.environments.executor.host | default (printf "http://proxy.%s.svc.%s/v1" (include "appwrite.namespace" .) .Values.clusterDomain) | quote }}
  _APP_FUNCTIONS_RUNTIMES: {{ if .Values.environments.functions.runtimes }}{{ (join "," .Values.environments.functions.runtimes) | quote }}{{ else }}{{ (print "php-8.0,node-18.0,python-3.9,ruby-3.1") | quote }}{{ end }}
  _APP_MAINTENANCE_INTERVAL: {{ .Values.environments.maintenance.interval | quote }}
  _APP_MAINTENANCE_RETENTION_CACHE: {{ .Values.environments.maintenance.retention.cache | quote }}
  _APP_MAINTENANCE_RETENTION_EXECUTION: {{ .Values.environments.maintenance.retention.execution | quote }}
  _APP_MAINTENANCE_RETENTION_ABUSE: {{ .Values.environments.maintenance.retention.abuse | quote }}
  _APP_MAINTENANCE_RETENTION_AUDIT: {{ .Values.environments.maintenance.retention.audit | quote }}
  _APP_USAGE_AGGREGATION_INTERVAL: {{ .Values.environments.usage.aggregationInterval | quote }}
  _APP_MAINTENANCE_RETENTION_USAGE_HOURLY: {{ .Values.environments.maintenance.retention.usageHourly | quote }}
  _APP_MAINTENANCE_RETENTION_SCHEDULES: {{ .Values.environments.maintenance.retention.schedules | quote }}
  _APP_USAGE_STATS: {{ .Values.environments.usage.stats | quote }}
  _APP_LOGGING_PROVIDER: {{ .Values.environments.logging.provider | quote }}
  _APP_LOGGING_CONFIG: {{ .Values.environments.logging.config | quote }}
  _APP_GRAPHQL_MAX_BATCH_SIZE: {{ .Values.environments.graphql.maxBatchSize | quote }}
  _APP_GRAPHQL_MAX_COMPLEXITY: {{ .Values.environments.graphql.maxComplexity | quote }}
  _APP_GRAPHQL_MAX_DEPTH: {{ .Values.environments.graphql.maxDepth | quote }}
  _APP_VCS_GITHUB_APP_NAME: {{ .Values.environments.vcs.github.appName | quote }}
  _APP_VCS_GITHUB_APP_ID: {{ .Values.environments.vcs.github.appId | quote }}
  _APP_VCS_GITHUB_CLIENT_ID: {{ .Values.environments.vcs.github.clientId | quote }}
  _APP_MIGRATIONS_FIREBASE_CLIENT_ID: {{ .Values.environments.migrations.firebase.clientId | quote }}
{{- end }}