# Copyright Marton Schneider
# SPDX-License-Identifier: APACHE-2.0

apiVersion: v2
name: appwrite-helm
description: An unofficial Helm chart to deploy Appwrite
keywords:
  - "Appwrite"
  - "appwrite"
icon: "https://appwrite.io/images/logos/logo.svg"
type: application
version: 0.1.7
appVersion: "1.4.13"
kubeVersion: ">=1.26"
deprecated: false
dependencies:
  - name: redis
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb
    version: 14.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 4.12.5
    repository: https://helm.influxdata.com/
    condition: influxdb.enabled
maintainers:
  - name: Marton Schneider
    url: https://github.com/schneidermr